[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
clv = "734ZWmPmAMGSjCshLCJQRpPNiaWBQsdaZDkvP3MAGmLz"

[programs.devnet]
clv = "734ZWmPmAMGSjCshLCJQRpPNiaWBQsdaZDkvP3MAGmLz"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/txodds.json"

[scripts]
test = "cargo test"

[hooks]
